### ISSUE TITLE
Add datasource RBAC in the plugin

### ISSUE THREAD

**Issue by ckbedwell** [grafana/synthetic-monitoring-app#877]
## Problem

Despite the Synthetic Monitoring api doesn't support RBAC yet, the plugin does receive enough information from Grafana regarding the three datasources it relies on to know if a user has the right permissions to do certain actions. We should implement RBAC in the plugin ASAP to reduce escalations and so that we will be ready to add additional RBAC features when the api supports them.

## Completion criteria

Reference draft PR to help inform these steps: https://github.com/grafana/synthetic-monitoring-app/pull/876

The plugin can be in several different states dependent on what datasource permissions a user has. At the moment it is difficult to reason with what state the plugin can be in as a lot of important information is all added in the `InstanceContext`. The first steps to considering this ticket complete are to split the instance context up into three separate contexts:

```[tasklist]
### Ground work
- [x] `MetaContext` and to create a meta data 'gate' to verifies that the meta data we expect is present instead of having a lot of type casting / optional chaining in consuming components: https://github.com/grafana/synthetic-monitoring-app/pull/878
- [x] `SMDatasourceContext` - if this isn't available or set-up access to the plugin is impossible: https://github.com/grafana/synthetic-monitoring-app/pull/879
- [x] Logs and metrics hooks - there should be a single source of truth for these across the application. https://github.com/grafana/synthetic-monitoring-app/pull/880
```

Related tickets:
https://github.com/grafana/synthetic-monitoring-app/issues/845
https://github.com/grafana/synthetic-monitoring-app/issues/846

```[tasklist]
### Meat and bones
- [ ] Unify where the datasources are read from and ensure they provide what RBAC permissions a user has
- [ ] Create a permissions feature with relevant context / components which support RBAC features
- [ ] Ensure the config pages are useful / correct for each area they can be displayed in dependent on the users' permissions
```

All of the above are addressed in: https://github.com/grafana/synthetic-monitoring-app/pull/883

## Additional context

Please read the RBAC docs in `grafana/plugin-tools`: https://github.com/grafana/plugin-tools/pull/1019
