### ISSUE TITLE
feat: secrets management POC

### ISSUE THREAD

**Issue by w1kman** [grafana/synthetic-monitoring-app#987]
**What would you like to be added**: A proof of concept implementation/demo of Secrets Management.

**Why is this needed**:
It will allow us to iterate on the UI/UX whilst the core feature is still in development.

**Task list**

- [x] Rework the ConfigPage so that it is tabbed (to prepare for "Secrets" tab).
  - [x] Create a tabbed layout to replace the current `ConfigPage`
  - [x] Split `configPage()` usage and app config into two different components
- [x] Create "Secrets" tab (behind featureToggle)
  - [x] Add a basic layout for creating and viewing secrets (view only shows name of secret, no reveal functionality).

**Comment by w1kman** [comment]
PR for creating tabbed layout for the config page.
https://github.com/grafana/synthetic-monitoring-app/pull/990
